default: src/com/gradescope/DoubleQueue/code/ArrayDoubleQueue.java src/com/gradescope/DoubleQueue/code/IDoubleQueue.java src/com/gradescope/DoubleQueue/code/ListDoubleQueue.java src/Driver/DoubleQueueDriver.java
	javac src/com/gradescope/DoubleQueue/code/ArrayDoubleQueue.java src/com/gradescope/DoubleQueue/code/IDoubleQueue.java src/com/gradescope/DoubleQueue/code/ListDoubleQueue.java src/Driver/DoubleQueueDriver.java


run: src/Driver/DoubleQueueDriver.class
	java src.Driver.DoubleQueueDriver

clean:
	rm -f *.class

