default: com/gradescope/DoubleQueue/code/ArrayDoubleQueue.java com/gradescope/DoubleQueue/code/IDoubleQueue.java com/gradescope/DoubleQueue/code/ListDoubleQueue.java Driver/DoubleQueueDriver.java
	javac com/gradescope/DoubleQueue/code/ArrayDoubleQueue.java com/gradescope/DoubleQueue/code/IDoubleQueue.java com/gradescope/DoubleQueue/code/ListDoubleQueue.java Driver/DoubleQueueDriver.java


run: Driver/DoubleQueueDriver.class
	java Driver.DoubleQueueDriver

clean: 
	rm -f  Driver/DoubleQueueDriver.class com/gradescope/DoubleQueue/code/ *.class 

